### ISSUE TITLE
set up paper build

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy-articles#8] opened 2018-02-05 00:39 UTC
We need:

- a Makefile to build the paper
- TravisCI or CircleCI to rebuild the paper on merges into or pushes to master.
- Uploading the built pdf to a fixed location, and link that from the README.

**Comment by rgommers** [comment] 2018-02-05 00:52
@person142 volunteered for this if we go with the LaTeX + Makefile option (thanks!), which it looks like we are.

**Comment by rgommers** [comment] 2018-02-05 00:53
Bonus points to implement the suggestion of @pv:

If you want to edit someone else's part, I think small changes should
be possible to do without asking. For larger changes, I suggest to add
instead a comment macro of the type `\PV{some comment}`, `\RG{some
comment}` in the text that explains the issue. Or, go with github issues
or PRs in those cases where you explicitly want feedback before
proceeding.

**Comment by charris** [comment] 2018-02-05 01:04
Thought I post this link about copyright because the issue is bound to come up at some point. https://academia.stackexchange.com/questions/7/does-publishing-a-paper-on-arxiv-prevent-me-from-submitting-it-to-a-non-open-acc

**Comment by ilayn** [comment] 2018-02-05 01:17
The macros are already implemented in [`changes`](https://tex.stackexchange.com/a/65466/3235) package.

**Comment by ilayn** [comment] 2018-02-05 02:27
Never had a problem of that sort but I don't have a strong opinion about the toolchain (yet). I am not sure if we would really need much of this kind comments anyhow if we keep the TeX files on GitHub and use the review system.  Especially if we separate things and make a master file with a lot of 

    ...
    \input{history}
    \input{modules}
    ...
etc. Then each section can be reviewed separately.

**Comment by perimosocordiae** [comment] 2018-02-05 14:39
For the Makefile, I'll recommend using `latexmk`: https://tex.stackexchange.com/a/40759/5105

I used it for several papers and my dissertation, with no complaints.

**Comment by tylerjereddy** [comment] 2018-02-05 18:11
+1 for `latexmk` as well; writing scripts that try to compile i.e., N times to get the citations right, etc., can get messy pretty quickly

**Comment by person142** [comment] 2018-02-22 18:56
Closing--done in gh-12.

**Closed by person142** 2018-02-22 18:56 UTC
Labels: task
